### ISSUE TITLE
How do I use this program?

### ISSUE THREAD

**Issue by SokroKalimi** [admin-else/infinity-scrape#1]
I'm not good at technical knowledge things, and the installation guide doesn't make any sense. Where do I use the git clone command? It doesn't work in Python.

edit: I've got it working, but I'm still confused.

**Comment by StrawberryLexta** [comment]
I am trying figure this out as well, so far I 
installed github desktop, python, git
made a project in github desktop "scrape" 
added pip.pyz to /scrape/ 
ran (windows so no $)
git clone https://github.com/admin-else/infinity-scrape
then
pip.pyz install -r infinity-scrape/requirements.txt
then
py howtoget.py

this gives me "what do you want: "
but returns 

Traceback (most recent call last):
  File "C:\Users\StrawberryBox\Documents\GitHub\ScrapeTest\infinity-scrape\howtoget.py", line 18, in <module>
    c.execute("SELECT ingr1, ingr2 FROM combination WHERE out = ?", [target])
sqlite3.OperationalError: no such table: combination

and that's where im stuck 

-->update: figured it out, need build new combinations with *(or use the infinite-craft.db file)
py infinity-scrape/scrape.py
ctrl + c (to end and save recipes)
then 
py infinity-scrape/howtoget.py
to search for a found recipe tree

requires to get working (windows)
https://desktop.github.com
https://git-scm.com/download/win
https://www.python.org/downloads/
https://bootstrap.pypa.io/pip/pip.pyz (auto downloads pip.pyz)(add to project in documents/github/"project name")

in github desktop setup repo then use repository/command prompt
run commands (git clone, pip.pyz install, scrape, howtoget)

** after cloning the repo the "infinite-craft.db" was in (/"projectname"/infinity-scrape) and would get the no table error, moving it to (/"projectname"/infinite-craft.db) allowed search it and scrape for new

**Comment by SokroKalimi** [comment]
![image](https://github.com/admin-else/infinity-scrape/assets/73545070/5d5d4abc-7443-4882-b317-37c960af5511)

**Comment by SokroKalimi** [comment]
I'm about this far, but I can't get farther. When I try the commands after "git clone https://github.com/admin-else/infinity-scrape", nothing happens.



![image](https://github.com/admin-else/infinity-scrape/assets/73545070/f00f0c58-fdf4-4b27-8340-5913905aa04c)

**Comment by StrawberryLexta** [comment]
I think this is what it needs, reading the page again, I think it needs discover items, so ran scrape.py and its collecting results, but looks like would take a long time populate

![image_2024-02-17_063114449](https://github.com/admin-else/infinity-scrape/assets/160323032/3eefbcb6-a81e-4d95-94f7-c8f5ba27d951)
![image_2024-02-17_063908304](https://github.com/admin-else/infinity-scrape/assets/160323032/b1a5d6bd-bc53-46db-9d87-16109e6d0066)

**Comment by admin-else** [comment]
hello

**Comment by admin-else** [comment]
i dont know why i didnt pick up the existing database if you cloned it it should pickup the existing db...

(edit make sure you are in the correct directory) if you are not things like errors like the one described here

https://github.com/admin-else/infinity-scrape/issues/1#issuecomment-1950052379
or here
File "C:\Users\StrawberryBox\Documents\GitHub\ScrapeTest\infinity-scrape\howtoget.py", line 18, in
c.execute("SELECT ingr1, ingr2 FROM combination WHERE out = ?", [target])
sqlite3.OperationalError: no such table: combination

ill add a check for the database existing
