### ISSUE TITLE
Issue with scraper.py

### ISSUE THREAD

**Issue by BigBowlORice** [admin-else/infinity-scrape#10]
when I run scraper.py it says 

Connecting to database...
Connected!
Starting, press CTRL+C or close this window to stop
Done...

and sits for a little bit and throws an error and says
<class 'requests.exceptions.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
Found 0 new combinations and 0 first ever combinations!

**Comment by admin-else** [comment]
Can you provide me with more information of how i may reproduce this behaivour like 
- os 
- current directory
- if infite craft is blocked by anything
- version of my project you used

etc.

i suspect you are being blocked in some way it not being able to decode expected json may mean that cloudflare blocked you.

**Comment by admin-else** [comment]
i ran the scraper for a few minutes and got the same error but i didnt have any debugging present.
i am rerunning it with debugging enabled some of my debugging tools.
