### ISSUE TITLE
Scrape.py going through different combinations but not receiving andy of the output

### ISSUE THREAD

**Issue by BigBowlORice** [admin-else/infinity-scrape#11]
It goes through different objects but gives an exception on the line
![image](https://github.com/user-attachments/assets/a11aad51-25bf-48ac-abaf-357b9e8dc588)

**Comment by admin-else** [comment]
clownlare is blocking your requests it would be annoying to implement anti clownflare stuff so i do not sadly plan to support clownflare bypassing.
