### ISSUE TITLE
Error: UNIQUE constraint failed: conbination.out

### ISSUE THREAD

**Issue by RedZebra123H** [admin-else/infinity-scrape#3]
When I run scrape.py, I sometimes get this error: Error: UNIQUE constraint failed: conbination.out

How do I fix this?

**Comment by admin-else** [comment]
i keep closing issues sorry wait

**Comment by admin-else** [comment]
can you provide more detail such as a full stack trace and if it crashes afterwards

**Comment by RedZebra123H** [comment]
i actually figured it out. i ran multiple tabs of the scrape.py. if i only ran 1 for long periods of time, it basically never stops.

**Comment by RedZebra123H** [comment]
I have a new issue. I start scape.py and it just says "Error:" after about 15 seconds.

![image](https://github.com/admin-else/infinity-scrape/assets/155842336/b069af99-c563-4149-8a47-74c17fa2b124)

**Comment by admin-else** [comment]
I will change the scrape.py error-printing-thing not to print empty errors tomorrow this is likey a error without description.

**Comment by admin-else** [comment]
added print type
