### ISSUE TITLE
Ratelimits

### ISSUE THREAD

**Issue by TheOnlyWayUp** [admin-else/infinity-scrape#9]
Current implementation:
https://github.com/admin-else/infinity-scrape/blob/b45670a776a5bc0ff0b2627d746574618a8262f9/scrape.py#L72-L79

Suggested implementation:
Exponential backoff using the [`backoff`](https://pypi.org/project/backoff/) library.

**Comment by admin-else** [comment]
ill do that later its 23:08 for me rn so kinda late hopefully fix tommorow around 8 or so

**Comment by admin-else** [comment]
fixed probably only tried it for a few minutes but should work i think
